default_platform(:ios)

platform :ios do
    lane :setup_distribution_cert do
        setup_ci
        match(
            git_url: "https://github.com/mapbox/apple-certificates.git",
            type: "appstore",
            readonly: true,
            skip_provisioning_profiles: true,
            app_identifier: []
        )
    end
end
