name: Build and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: swift build

      - name: Test
        run: swift test

  build-and-test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode_version: ['14.3.1', '15.2.0']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "${{ matrix.xcode_version }}"

      - name: Build
        run: xcodebuild -scheme Turf -configuration Debug -destination 'platform=macOS' build

      - name: Test
        run: xcodebuild -scheme Turf -configuration Debug -destination 'platform=macOS' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  test-simulator:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: 
          - "platform=visionOS Simulator,OS=1.0,name=Apple Vision Pro"
          - "platform=iOS Simulator,OS=17.2,name=iPhone 15"
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Simulator Tests
        run: |
          xcodebuild test \
            -scheme Turf \
            -destination "${{ matrix.destination }}" \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

  create-xcframework:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: configure aws credentials
        uses: mapbox/configure-aws-credentials-internal@v5
        with:
          target-account-id: ${{ vars.AWS_ACCOUNT_ID_DEFAULT }}

      - name: setup GH reader token
        uses: mapbox/setup-github-tokens@v2
        with:
          scope-type: 'reader'

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2.0'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Code Signing
        run: |
          bundle install
          bundle exec fastlane setup_distribution_cert
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ env.GITHUB_READER_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Build and create XCFramework
        run: ./scripts/xcframework.sh ./Turf.xcframework.zip
